import { jsPDF } from 'jspdf';
import { Capacitor } from '@capacitor/core';
import { Filesystem, Directory } from '@capacitor/filesystem';
import { Share } from '@capacitor/share';
import type { Receipt, Tool, Hydrated } from './useRecords';

// Turn a list of receipts or tools into a PDF and hand it to the native share
// sheet (iOS/Android) or trigger a browser download. Same pattern as
// saveImage.ts / backup.ts — one path for native, one for web.
//
// Layout is a 2-column card grid: photo on the left of each card, details on
// the right. Fits 10 cards per A4 page (5 rows × 2 cols).

const PAGE_W = 595.28; // pt, A4
const PAGE_H = 841.89;
const MARGIN = 30;
const HEADER_H = 50;
const FOOTER_H = 20;
const NUM_COLS = 2;
const COL_GAP = 14;
const ROW_GAP = 10;
const CARD_W = (PAGE_W - MARGIN * 2 - COL_GAP * (NUM_COLS - 1)) / NUM_COLS;
const CARD_PAD = 8;
const THUMB_W = 96;
const THUMB_H = 124;
const CARD_H = THUMB_H + CARD_PAD * 2;
const CONTENT_TOP = MARGIN + HEADER_H;
const CONTENT_BOTTOM = PAGE_H - FOOTER_H;
const NUM_ROWS = Math.floor((CONTENT_BOTTOM - CONTENT_TOP + ROW_GAP) / (CARD_H + ROW_GAP));
const CARDS_PER_PAGE = NUM_COLS * NUM_ROWS;

function fmtMoney(n: number | undefined): string {
  if (n == null || !isFinite(n)) return '—';
  return `$${n.toFixed(2)}`;
}

function fmtDate(iso: string | undefined, fallback: number): string {
  const src = iso ? new Date(iso) : new Date(fallback);
  if (isNaN(src.getTime())) return '—';
  return src.toLocaleDateString(undefined, { day: 'numeric', month: 'short', year: 'numeric' });
}

// ── Header / footer ─────────────────────────────────────────────────────────

function drawHeader(doc: jsPDF, title: string, leftSub: string, rightBig: string, rightSub?: string) {
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.setTextColor(25);
  doc.text(title, MARGIN, MARGIN + 14);

  if (leftSub) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9.5);
    doc.setTextColor(120);
    doc.text(leftSub, MARGIN, MARGIN + 30);
  }

  if (rightSub) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(120);
    doc.text(rightSub, PAGE_W - MARGIN, MARGIN + 12, { align: 'right' });
  }

  if (rightBig) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    doc.setTextColor(25);
    doc.text(rightBig, PAGE_W - MARGIN, MARGIN + 30, { align: 'right' });
  }

  doc.setDrawColor(220);
  doc.setLineWidth(0.5);
  doc.line(MARGIN, MARGIN + 42, PAGE_W - MARGIN, MARGIN + 42);
}

function drawFooter(doc: jsPDF, pageNum: number, pageCount: number, logoDataUrl: string | null) {
  const baseline = PAGE_H - 8;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(140);

  // Left: "Generated by" + wordmark logo (or fall back to "Generated by Setout")
  const prefix = 'Generated by ';
  doc.text(prefix, MARGIN, baseline);
  const prefixW = doc.getTextWidth(prefix);

  let logoDrawn = false;
  if (logoDataUrl) {
    try {
      // Wordmark is ~2.55:1 wide — draw at 40×16pt so it sits centred on the
      // text baseline (visual centre ≈ PAGE_H - 10).
      doc.addImage(logoDataUrl, 'PNG', MARGIN + prefixW, PAGE_H - 18, 40, 16, undefined, 'FAST');
      logoDrawn = true;
    } catch {
      /* fall through — text-only footer */
    }
  }
  if (!logoDrawn) {
    doc.text('Setout', MARGIN + prefixW, baseline);
  }

  // Right: page counter
  doc.text(`Page ${pageNum} of ${pageCount}`, PAGE_W - MARGIN, baseline, { align: 'right' });
}

// ── Card rendering ──────────────────────────────────────────────────────────

interface DetailLine {
  value: string | undefined;
  bold?: boolean;
  size?: number;
  color?: number;
  maxLines?: number;
  gapAfter?: number;
}

function textLine(
  doc: jsPDF,
  x: number,
  cursor: number,
  text: string,
  opts: { bold?: boolean; size: number; color: number; width: number; maxLines?: number; gapAfter?: number },
): number {
  doc.setFont('helvetica', opts.bold ? 'bold' : 'normal');
  doc.setFontSize(opts.size);
  doc.setTextColor(opts.color);
  const wrapped = doc.splitTextToSize(text, opts.width).slice(0, opts.maxLines ?? 1);
  const lineH = opts.size * 1.2;
  const baseline = cursor + opts.size;
  doc.text(wrapped, x, baseline);
  return cursor + lineH * wrapped.length + (opts.gapAfter ?? 2);
}

function drawCard(doc: jsPDF, x: number, y: number, thumb: string | undefined, lines: DetailLine[]) {
  // subtle rounded border
  doc.setDrawColor(230);
  doc.setLineWidth(0.5);
  doc.roundedRect(x, y, CARD_W, CARD_H, 4, 4);

  const px = x + CARD_PAD;
  const py = y + CARD_PAD;

  // photo (or placeholder)
  if (thumb) {
    try {
      doc.addImage(thumb, 'JPEG', px, py, THUMB_W, THUMB_H, undefined, 'FAST');
    } catch {
      /* skip broken image */
    }
  } else {
    doc.setFillColor(245, 245, 245);
    doc.rect(px, py, THUMB_W, THUMB_H, 'F');
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(170);
    doc.text('No photo', px + THUMB_W / 2, py + THUMB_H / 2, { align: 'center', baseline: 'middle' });
  }

  // details right of photo
  const dx = px + THUMB_W + 10;
  const dw = CARD_W - CARD_PAD * 2 - THUMB_W - 10;
  let cursor = py;

  for (const line of lines) {
    if (!line.value) continue;
    cursor = textLine(doc, dx, cursor, line.value, {
      bold: line.bold,
      size: line.size ?? 9,
      color: line.color ?? 90,
      width: dw,
      maxLines: line.maxLines ?? 1,
      gapAfter: line.gapAfter ?? 2,
    });
    // stop if we've run out of vertical room in the card
    if (cursor > py + THUMB_H - 4) break;
  }
}

// ── Page loop ───────────────────────────────────────────────────────────────

function positionForIndex(indexOnPage: number): { x: number; y: number } {
  const col = indexOnPage % NUM_COLS;
  const row = Math.floor(indexOnPage / NUM_COLS);
  return {
    x: MARGIN + col * (CARD_W + COL_GAP),
    y: CONTENT_TOP + row * (CARD_H + ROW_GAP),
  };
}

function renderCards<T>(
  doc: jsPDF,
  items: T[],
  header: { title: string; leftSub: string; rightBig: string; rightSub?: string },
  buildCard: (item: T) => { thumb: string | undefined; lines: DetailLine[] },
  logoDataUrl: string | null,
) {
  const pageCount = Math.max(1, Math.ceil(items.length / CARDS_PER_PAGE));
  let pageNum = 1;
  drawHeader(doc, header.title, header.leftSub, header.rightBig, header.rightSub);

  for (let i = 0; i < items.length; i++) {
    if (i > 0 && i % CARDS_PER_PAGE === 0) {
      drawFooter(doc, pageNum, pageCount, logoDataUrl);
      doc.addPage();
      pageNum++;
      drawHeader(doc, header.title, header.leftSub, header.rightBig, header.rightSub);
    }
    const indexOnPage = i % CARDS_PER_PAGE;
    const { x, y } = positionForIndex(indexOnPage);
    const { thumb, lines } = buildCard(items[i]);
    drawCard(doc, x, y, thumb, lines);
  }

  drawFooter(doc, pageNum, pageCount, logoDataUrl);
}

// ── Receipts ────────────────────────────────────────────────────────────────

export function buildReceiptsPdf(items: Hydrated<Receipt>[], periodLabel?: string, logoDataUrl: string | null = null): jsPDF {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const total = items.reduce((s, h) => s + (h.record.amount ?? 0), 0);
  const countStr = `${items.length} receipt${items.length === 1 ? '' : 's'}`;

  let periodStr = periodLabel ?? '';
  if (!periodStr) {
    const dates = items.map(h => (h.record.date ? new Date(h.record.date).getTime() : h.record.timestamp));
    const from = dates.length ? new Date(Math.min(...dates)) : null;
    const to = dates.length ? new Date(Math.max(...dates)) : null;
    periodStr = from && to
      ? `${from.toLocaleDateString(undefined, { day: 'numeric', month: 'short', year: 'numeric' })} – ${to.toLocaleDateString(undefined, { day: 'numeric', month: 'short', year: 'numeric' })}`
      : '';
  }
  const leftSub = periodStr ? `${countStr} · ${periodStr}` : countStr;

  renderCards(
    doc,
    items,
    { title: 'Receipts', leftSub, rightBig: fmtMoney(total) },
    ({ record, dataUrl }) => ({
      thumb: dataUrl ?? undefined,
      lines: [
        { value: record.supplier, bold: true, size: 11, color: 25, gapAfter: 3 },
        { value: record.amount != null ? fmtMoney(record.amount) : undefined, bold: true, size: 13, color: 25, gapAfter: 5 },
        { value: fmtDate(record.date, record.timestamp), size: 9, color: 120, gapAfter: 2 },
        { value: record.category, size: 9, color: 120, gapAfter: 4 },
        { value: record.notes, size: 9, color: 100, maxLines: 3, gapAfter: 0 },
      ],
    }),
    logoDataUrl,
  );

  return doc;
}

// ── Tools ───────────────────────────────────────────────────────────────────

export function buildToolsPdf(items: Hydrated<Tool>[], logoDataUrl: string | null = null): jsPDF {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const total = items.reduce((s, h) => s + (h.record.replacementValue ?? 0), 0);
  const leftSub = `${items.length} item${items.length === 1 ? '' : 's'}`;

  renderCards(
    doc,
    items,
    { title: 'Tool inventory', leftSub, rightBig: fmtMoney(total), rightSub: 'Total replacement value' },
    ({ record, dataUrl }) => {
      const brandModel = [record.brand, record.model].filter(Boolean).join(' ');
      return {
        thumb: dataUrl ?? undefined,
        lines: [
          { value: record.name, bold: true, size: 11, color: 25, gapAfter: 3 },
          { value: brandModel || undefined, size: 9, color: 100, gapAfter: 4 },
          { value: record.replacementValue != null ? fmtMoney(record.replacementValue) : undefined, bold: true, size: 12, color: 25, gapAfter: 4 },
          { value: record.serial ? `S/N ${record.serial}` : undefined, size: 9, color: 120, gapAfter: 2 },
          { value: record.purchaseDate ? `Purchased ${fmtDate(record.purchaseDate, record.timestamp)}` : undefined, size: 9, color: 120, gapAfter: 2 },
          { value: record.category, size: 9, color: 120, gapAfter: 3 },
          { value: record.notes, size: 9, color: 100, maxLines: 2, gapAfter: 0 },
        ],
      };
    },
    logoDataUrl,
  );

  return doc;
}

// ── Share helper ────────────────────────────────────────────────────────────

// On native, write the PDF to Cache and hand its file:// URI to the share sheet
// (Mail / Files / iCloud Drive / AirDrop / WhatsApp / etc.). On web, trigger a
// browser download. Mirrors saveImage.ts and backup.ts.
export async function sharePdf(doc: jsPDF, filename: string, title: string): Promise<void> {
  if (Capacitor.isNativePlatform()) {
    try {
      const dataUri = doc.output('datauristring');
      const commaIdx = dataUri.indexOf(',');
      const base64 = commaIdx >= 0 ? dataUri.slice(commaIdx + 1) : dataUri;

      const written = await Filesystem.writeFile({
        path: filename,
        data: base64,
        directory: Directory.Cache,
      });
      await Share.share({
        title,
        url: written.uri,
        dialogTitle: title,
      });
      return;
    } catch (err) {
      if ((err as Error)?.message?.toLowerCase().includes('cancel')) return;
      console.warn('[recordsExport] native share failed, falling back to browser download', err);
    }
  }

  doc.save(filename);
}

function todayStamp(): string {
  const now = new Date();
  return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')}`;
}

// Load the app logo once per export for the footer. Fetches from the bundled
// public path — resolves in dev, prod, and Capacitor native (all serve `/`
// from the same root). Returns null if the fetch fails so the PDF still
// renders with a text-only footer.
let logoPromise: Promise<string | null> | null = null;
function loadLogoDataUrl(): Promise<string | null> {
  if (logoPromise) return logoPromise;
  logoPromise = (async () => {
    try {
      const res = await fetch('/logo-wordmark.png');
      if (!res.ok) return null;
      const blob = await res.blob();
      return await new Promise<string>((resolve, reject) => {
        const reader = new FileReader();
        reader.onload = () => resolve(reader.result as string);
        reader.onerror = () => reject(reader.error);
        reader.readAsDataURL(blob);
      });
    } catch {
      return null;
    }
  })();
  return logoPromise;
}

export async function exportReceipts(items: Hydrated<Receipt>[], periodLabel?: string): Promise<void> {
  if (items.length === 0) return;
  const logo = await loadLogoDataUrl();
  const doc = buildReceiptsPdf(items, periodLabel, logo);
  await sharePdf(doc, `setout-receipts-${todayStamp()}.pdf`, 'Setout receipts');
}

export async function exportTools(items: Hydrated<Tool>[]): Promise<void> {
  if (items.length === 0) return;
  const logo = await loadLogoDataUrl();
  const doc = buildToolsPdf(items, logo);
  await sharePdf(doc, `setout-tools-${todayStamp()}.pdf`, 'Setout tool inventory');
}
