#!/bin/sh
# Xcode Cloud runs this automatically right after cloning the repo, before
# any build/archive step. ios/App/App/public and capacitor.config.json are
# git-ignored (see ios/.gitignore) — they're generated by `cap sync` and
# regenerated locally by every `npm run build:ios`. Xcode Cloud's checkout
# never ran that build step, so those files simply didn't exist, and the
# Archive step failed with "capacitor.config.json couldn't be opened" /
# "public couldn't be opened". This script regenerates them before Xcode
# Cloud tries to compile.
set -e

brew install node

cd "$CI_PRIMARY_REPOSITORY_PATH"
npm ci
npm run build:ios
