import { useState, useContext, useRef } from 'react';
import { CalcHeader } from '../components/CalcHeader';
import { ResultCard } from '../components/ResultCard';
import { AddToJobPrompt } from '../components/AddToJobPrompt';
import { JobNameInput } from '../components/JobNameInput';
import { COMPLIANCE_NOTES } from '../lib/compliance';
import { SettingsContext, HistoryContext } from '../contexts';

interface Material {
  item: string;
  quantity: number;
  unit: string;
  note: string;
}

interface QuoteResult {
  dimensions: { lengthM: number; widthM: number; areaM2: number };
  materials: Material[];
  labourHours: number;
  assumptions: string[];
}

function fileToBase64(file: File): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => {
      const result = reader.result as string;
      resolve(result.slice(result.indexOf(',') + 1));
    };
    reader.onerror = reject;
    reader.readAsDataURL(file);
  });
}

export function PhotoQuoteCalc() {
  const { settings } = useContext(SettingsContext);
  const { addEntry, updateEntry } = useContext(HistoryContext);

  const [photo, setPhoto] = useState<File | null>(null);
  const [photoPreview, setPhotoPreview] = useState('');
  const [description, setDescription] = useState('');
  const [result, setResult] = useState<QuoteResult | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [jobName, setJobName] = useState('');
  const [lastEntryId, setLastEntryId] = useState('');
  const [copied, setCopied] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  function handlePhotoChange(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0];
    if (!file) return;
    setPhoto(file);
    setPhotoPreview(URL.createObjectURL(file));
    setResult(null);
    setError('');
  }

  async function handleGenerate() {
    if (!photo || !description.trim() || loading) return;

    setLoading(true);
    setError('');
    setResult(null);

    try {
      const imageBase64 = await fileToBase64(photo);
      const res = await fetch('/api/quote', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ imageBase64, mediaType: photo.type, description: description.trim() }),
      });

      if (!res.ok) {
        const body = await res.text();
        throw new Error(`Estimate failed (${res.status}): ${body}`);
      }

      const quote = (await res.json()) as QuoteResult;
      setResult(quote);

      const id = crypto.randomUUID();
      setLastEntryId(id);
      addEntry({
        id,
        calculatorId: 'photoquote',
        timestamp: Date.now(),
        inputs: { description: description.trim() },
        outputs: {
          areaM2: quote.dimensions.areaM2,
          labourHours: quote.labourHours,
          materialCount: quote.materials.length,
        },
      });

      if (navigator.vibrate) navigator.vibrate(30);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Something went wrong.');
    } finally {
      setLoading(false);
    }
  }

  function buildShareText(): string {
    if (!result) return '';
    const lines: string[] = [`Setout — Photo Quote${jobName ? ` — ${jobName}` : ''}`, ''];
    lines.push(`Estimated area: ${result.dimensions.lengthM}m × ${result.dimensions.widthM}m = ${result.dimensions.areaM2}m²`);
    lines.push('');
    lines.push('Materials');
    for (const m of result.materials) {
      lines.push(`• ${m.quantity} ${m.unit} — ${m.item}${m.note ? ` (${m.note})` : ''}`);
    }
    lines.push('');
    lines.push(`Estimated labour: ${result.labourHours} hours`);
    if (result.assumptions.length) {
      lines.push('');
      lines.push('Assumptions');
      for (const a of result.assumptions) lines.push(`• ${a}`);
    }
    lines.push('', 'Generated by Setout — verify on site before ordering');
    return lines.join('\n');
  }

  async function handleShare() {
    const text = buildShareText();
    if (typeof navigator.share === 'function') {
      try {
        await navigator.share({ title: 'Setout — Photo Quote', text });
        return;
      } catch (err) {
        if ((err as Error)?.name === 'AbortError') return;
      }
    }
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch { /* ignore */ }
  }

  const canGenerate = !!photo && description.trim().length > 0 && !loading;

  return (
    <div style={{ flex: 1, display: 'flex', flexDirection: 'column' }}>
      <CalcHeader title="Photo Quote" />

      <div style={{ padding: '24px 20px', display: 'flex', flexDirection: 'column', gap: 20 }}>

        {/* Photo capture */}
        <div>
          <input
            ref={fileInputRef}
            type="file"
            accept="image/*"
            capture="environment"
            onChange={handlePhotoChange}
            style={{ display: 'none' }}
          />
          {photoPreview ? (
            <button
              onClick={() => fileInputRef.current?.click()}
              style={{
                width: '100%', padding: 0, border: '0.5px solid var(--color-border)',
                borderRadius: 'var(--radius-card)', overflow: 'hidden', cursor: 'pointer',
                background: 'none', display: 'block',
              }}
            >
              <img src={photoPreview} alt="Job site" style={{ width: '100%', maxHeight: 260, objectFit: 'cover', display: 'block' }} />
            </button>
          ) : (
            <button
              onClick={() => fileInputRef.current?.click()}
              style={{
                width: '100%', padding: '40px 20px', background: 'var(--color-card)',
                border: '0.5px dashed rgba(0,0,0,0.18)', borderRadius: 'var(--radius-card)',
                display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 10,
                cursor: 'pointer', fontFamily: 'inherit',
              }}
            >
              <div style={{ width: 56, height: 56, borderRadius: 16, background: 'rgba(255,90,31,0.10)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                <svg width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="var(--color-orange)" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z" />
                  <circle cx="12" cy="13" r="4" />
                </svg>
              </div>
              <p style={{ margin: 0, fontSize: 15, fontWeight: 500, color: 'var(--color-text)' }}>Take or upload a photo</p>
              <p style={{ margin: 0, fontSize: 12, color: 'var(--color-muted)' }}>The area you're quoting</p>
            </button>
          )}
        </div>

        {/* Description */}
        <div>
          <p style={{ margin: '0 0 8px', fontSize: 12, color: 'var(--color-muted)', fontWeight: 500 }}>WHAT'S THE JOB</p>
          <textarea
            value={description}
            onChange={e => setDescription(e.target.value)}
            placeholder="e.g. Treated pine deck, 4x4 posts, privacy screen one side, approx 6x4 metres"
            rows={3}
            style={{
              width: '100%', background: 'var(--color-card)', border: '0.5px solid var(--color-border)',
              borderRadius: 12, padding: '12px 14px', fontSize: 15, fontFamily: 'inherit',
              color: 'var(--color-text)', resize: 'none', outline: 'none', boxSizing: 'border-box', lineHeight: 1.5,
            }}
          />
        </div>

        {error && <p style={{ margin: 0, fontSize: 13, color: '#e53e3e', lineHeight: 1.5 }}>{error}</p>}

        <button
          onClick={handleGenerate}
          disabled={!canGenerate}
          style={{
            background: canGenerate ? 'var(--color-orange)' : 'var(--color-border)',
            color: '#fff', border: 'none', borderRadius: 14, padding: '16px',
            fontSize: 16, fontWeight: 500, fontFamily: 'inherit',
            cursor: canGenerate ? 'pointer' : 'default', letterSpacing: '-0.3px',
          }}
          onPointerDown={e => { if (canGenerate) e.currentTarget.style.opacity = '0.85'; }}
          onPointerUp={e => (e.currentTarget.style.opacity = '1')}
          onPointerLeave={e => (e.currentTarget.style.opacity = '1')}
        >
          {loading ? 'Estimating…' : 'Generate estimate'}
        </button>

        {result && (
          <>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10 }}>
              <ResultCard label="Area" value={result.dimensions.areaM2} unit="m²" accent />
              <ResultCard label="Labour" value={result.labourHours} unit="hrs" />
            </div>
            <p style={{ margin: 0, fontSize: 12, color: 'var(--color-muted)' }}>
              {result.dimensions.lengthM}m × {result.dimensions.widthM}m estimated from photo
            </p>

            <div style={{
              background: 'var(--color-card)', border: '0.5px solid var(--color-border)',
              borderRadius: 'var(--radius-card)', padding: '18px 16px',
              display: 'flex', flexDirection: 'column', gap: 10,
            }}>
              <p style={{ margin: 0, fontSize: 12, color: 'var(--color-muted)', fontWeight: 500 }}>MATERIALS</p>
              {result.materials.map((m, i) => (
                <div key={i} style={{ display: 'flex', justifyContent: 'space-between', gap: 10 }}>
                  <div style={{ flex: 1, minWidth: 0 }}>
                    <p style={{ margin: 0, fontSize: 14, color: 'var(--color-text)' }}>{m.item}</p>
                    {m.note && <p style={{ margin: '1px 0 0', fontSize: 11.5, color: 'var(--color-muted)' }}>{m.note}</p>}
                  </div>
                  <span style={{ fontSize: 14, color: 'var(--color-muted)', fontVariantNumeric: 'tabular-nums', flexShrink: 0 }}>
                    {m.quantity} {m.unit}
                  </span>
                </div>
              ))}
            </div>

            {result.assumptions.length > 0 && (
              <div style={{
                background: 'var(--color-card)', border: '0.5px solid var(--color-border)',
                borderRadius: 'var(--radius-card)', padding: '18px 16px',
                display: 'flex', flexDirection: 'column', gap: 8,
              }}>
                <p style={{ margin: 0, fontSize: 12, color: 'var(--color-muted)', fontWeight: 500 }}>ASSUMPTIONS — CHECK ON SITE</p>
                {result.assumptions.map((a, i) => (
                  <p key={i} style={{ margin: 0, fontSize: 13.5, color: 'var(--color-text)', lineHeight: 1.5 }}>• {a}</p>
                ))}
              </div>
            )}

            <JobNameInput value={jobName} onChange={setJobName} onSave={name => updateEntry(lastEntryId, { jobName: name })} />
            <AddToJobPrompt calculationId={lastEntryId} />

            <button
              onClick={handleShare}
              style={{
                display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8,
                width: '100%', padding: '12px 16px', borderRadius: 12,
                border: '0.5px solid var(--color-border)', background: copied ? '#22c55e' : 'var(--color-bg)',
                color: copied ? '#fff' : 'var(--color-text)', fontSize: 14, fontWeight: 500,
                fontFamily: 'inherit', cursor: 'pointer', letterSpacing: '-0.2px', transition: 'all 0.2s',
              }}
            >
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <path d="M4 12v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8" /><polyline points="16 6 12 2 8 6" /><line x1="12" y1="2" x2="12" y2="15" />
              </svg>
              {copied ? 'Copied' : 'Share quote'}
            </button>

            <p style={{ margin: 0, fontSize: 11, color: 'var(--color-muted)', lineHeight: 1.5 }}>
              {COMPLIANCE_NOTES.photoquote[settings.region]}
            </p>
          </>
        )}
      </div>
    </div>
  );
}
