import { useState } from 'react';
import { buildCutlistPdf } from '../lib/cutlistPdf';
import type { CutlistPdfSection } from '../lib/cutlistPdf';

interface DownloadCutlistButtonProps {
  calcName: string;
  jobName?: string;
  sections: CutlistPdfSection[];
}

export function DownloadCutlistButton({ calcName, jobName, sections }: DownloadCutlistButtonProps) {
  const [busy, setBusy] = useState(false);

  if (sections.length === 0) return null;

  async function handleDownload() {
    setBusy(true);
    try {
      const doc = buildCutlistPdf({ calcName, jobName, sections });
      const blob = doc.output('blob');
      const filename = `cutlist-${calcName.toLowerCase().replace(/\s+/g, '-')}.pdf`;
      const file = new File([blob], filename, { type: 'application/pdf' });

      if (
        typeof navigator.share === 'function' &&
        typeof navigator.canShare === 'function' &&
        navigator.canShare({ files: [file] })
      ) {
        await navigator.share({ files: [file], title: `${calcName} Cut List` });
      } else if (typeof navigator.share === 'function') {
        // Older iOS — share without file attachment
        await navigator.share({ title: `${calcName} Cut List`, text: 'Cut list generated by Setout' });
      } else {
        // Desktop browser fallback
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = filename;
        a.click();
        URL.revokeObjectURL(url);
      }
    } catch (err) {
      // AbortError = user cancelled the share sheet — silent
      if ((err as Error)?.name !== 'AbortError') console.error('Cut list download failed:', err);
    } finally {
      setBusy(false);
    }
  }

  return (
    <button
      onClick={handleDownload}
      disabled={busy}
      style={{
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        width: '100%',
        padding: '12px 16px',
        borderRadius: 12,
        border: '0.5px solid var(--color-border)',
        background: 'var(--color-bg)',
        color: busy ? 'var(--color-muted)' : 'var(--color-text)',
        fontSize: 14,
        fontWeight: 500,
        fontFamily: 'inherit',
        cursor: busy ? 'default' : 'pointer',
        letterSpacing: '-0.2px',
        opacity: busy ? 0.6 : 1,
      }}
      onPointerDown={e => { if (!busy) e.currentTarget.style.opacity = '0.7'; }}
      onPointerUp={e => { e.currentTarget.style.opacity = '1'; }}
      onPointerLeave={e => { e.currentTarget.style.opacity = '1'; }}
    >
      <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
        <polyline points="7 10 12 15 17 10" />
        <line x1="12" y1="15" x2="12" y2="3" />
      </svg>
      {busy ? 'Generating…' : 'Download cut list'}
    </button>
  );
}
