import { useContext, useState } from 'react';
import { HistoryContext } from '../contexts';
import { CALCULATORS } from '../lib/calculators';
import type { HistoryEntry } from '../types';

function humanize(key: string): string {
  return key
    .replace(/([A-Z])/g, ' $1')
    .replace(/[_-]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .replace(/^./, c => c.toUpperCase());
}

function formatValue(v: number | string): string {
  if (typeof v === 'string') return v;
  if (!Number.isFinite(v)) return '—';
  // Drop trailing .0 / .00 on whole or near-whole numbers
  return Number(v.toFixed(3)).toString();
}

export function buildShareText(entry: HistoryEntry): { title: string; body: string } {
  const meta = CALCULATORS.find(c => c.id === entry.calculatorId);
  const calcName = meta?.label ?? entry.calculatorId;
  const date = new Date(entry.timestamp).toLocaleDateString();

  const lines: string[] = [`Setout — ${calcName}`];
  if (entry.jobName) lines.push(`Job: ${entry.jobName}`);
  lines.push(`Date: ${date}`);
  lines.push('');

  const inputKeys = Object.keys(entry.inputs);
  if (inputKeys.length) {
    lines.push('Inputs');
    for (const k of inputKeys) lines.push(`• ${humanize(k)}: ${formatValue(entry.inputs[k])}`);
    lines.push('');
  }

  const outputKeys = Object.keys(entry.outputs);
  if (outputKeys.length) {
    lines.push('Results');
    for (const k of outputKeys) lines.push(`• ${humanize(k)}: ${formatValue(entry.outputs[k])}`);
    lines.push('');
  }

  if (entry.notes) {
    lines.push('Notes');
    lines.push(entry.notes);
    lines.push('');
  }

  lines.push('Generated by Setout');

  return { title: `Setout — ${calcName}`, body: lines.join('\n') };
}

interface ShareCalcButtonProps {
  calculationId: string;
  // When provided, share the given plain-text body (typically a shopping list)
  // instead of the full inputs/outputs dump. Title falls back to the calc name
  // if not given.
  shareBody?: string;
  shareTitle?: string;
}

export function ShareCalcButton({ calculationId, shareBody, shareTitle }: ShareCalcButtonProps) {
  const { history } = useContext(HistoryContext);
  const [toast, setToast] = useState<string | null>(null);

  if (!calculationId) return null;
  const entry = history.find(h => h.id === calculationId);
  if (!entry) return null;

  // Copy via a hidden textarea + execCommand — the only path that works over
  // http:// (insecure context), which is what WKWebView sees during live-reload dev
  // and what most old iOS Safari versions fall back to.
  function fallbackCopy(text: string): boolean {
    try {
      const ta = document.createElement('textarea');
      ta.value = text;
      ta.setAttribute('readonly', '');
      ta.style.position = 'fixed';
      ta.style.top = '0';
      ta.style.left = '0';
      ta.style.opacity = '0';
      document.body.appendChild(ta);
      ta.select();
      ta.setSelectionRange(0, text.length);
      const ok = document.execCommand('copy');
      document.body.removeChild(ta);
      return ok;
    } catch {
      return false;
    }
  }

  async function handleShare() {
    if (!entry) return;
    const defaults = buildShareText(entry);
    const title = shareTitle ?? defaults.title;
    const body = shareBody ?? defaults.body;

    if (typeof navigator !== 'undefined' && typeof navigator.share === 'function') {
      try {
        await navigator.share({ title, text: body });
        return;
      } catch (err) {
        // User cancelled — silent. Any other error → fall through to clipboard.
        if ((err as Error)?.name === 'AbortError') return;
      }
    }

    // Prefer the modern async clipboard API (needs secure context)
    if (typeof navigator !== 'undefined' && navigator.clipboard?.writeText) {
      try {
        await navigator.clipboard.writeText(body);
        setToast('Copied to clipboard');
        setTimeout(() => setToast(null), 2500);
        return;
      } catch {
        // fall through to the textarea trick
      }
    }

    if (fallbackCopy(body)) {
      setToast('Copied to clipboard');
      setTimeout(() => setToast(null), 2500);
    } else {
      setToast('Could not share or copy');
      setTimeout(() => setToast(null), 2500);
    }
  }

  return (
    <>
      <button
        onClick={handleShare}
        style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          gap: 8,
          width: '100%',
          padding: '12px 16px',
          borderRadius: 12,
          border: '0.5px solid var(--color-border)',
          background: 'var(--color-bg)',
          color: 'var(--color-text)',
          fontSize: 14,
          fontWeight: 500,
          fontFamily: 'inherit',
          cursor: 'pointer',
          letterSpacing: '-0.2px',
        }}
        onPointerDown={e => (e.currentTarget.style.opacity = '0.7')}
        onPointerUp={e => (e.currentTarget.style.opacity = '1')}
        onPointerLeave={e => (e.currentTarget.style.opacity = '1')}
        aria-label="Share calculation"
      >
        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
          <path d="M4 12v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8" />
          <polyline points="16 6 12 2 8 6" />
          <line x1="12" y1="2" x2="12" y2="15" />
        </svg>
        Share calculation
      </button>

      {toast && (
        <div style={{
          position: 'fixed', bottom: 100, left: '50%', transform: 'translateX(-50%)',
          zIndex: 1001, background: '#0a0a0a', color: '#fff',
          borderRadius: 20, padding: '10px 20px',
          fontSize: 14, fontWeight: 500, whiteSpace: 'nowrap', pointerEvents: 'none',
        }}>
          {toast}
        </div>
      )}
    </>
  );
}
